openapi: 3.0.3
info:
  title: Lago API documentation
  description: |-
    Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
  contact:
    email: tech@getlago.com
  version: 0.28.0-beta
externalDocs:
  description: Lago Github
  url: https://github.com/getlago

