name: Add tags

on:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run read-yaml action
        id: openapi
        uses: jbutcher5/read-yaml@main
        with:
          file: './openapi.yaml'
          key-path: '["info", "version"]'

      - name: Display OpenAPI version
        run: echo "${{ steps.openapi.outputs.data }}"

